### ISSUE TITLE
LR1110 Busy pin always high after firmware updation

### ISSUE THREAD

**Issue by kvkc97** [Lora-net/lr1110_updater_tool#2]
I used Updater tool to update the firmware to modem 1.0.7. During firmware updation, I noticed using LED status that flashing of firmware was completed, however following switch case to update to TX or MODEM was not executed. To identify the problem, I tried to reprogram the IC and check where the code got stuck. But on further execution of the code the BUSY pin was always high and no command could be executed after system reset. What could have been the issue here?

**Comment by matthieuantoine** [comment]
Can you please share the log printed on the serial COM port?

See [here](https://github.com/Lora-net/lr1110_updater_tool#operations) for serial COM port configuration.

**Comment by kvkc97** [comment]
I have ported the code to STM32WB55RG Controller to be used in a custom board so the COM messages will not be displayed. The firmware seems to be corrupted and stuck at the first command send to LR1110. How can we enter DFU mode and update the firmware?

**Comment by matthieuantoine** [comment]
Here is the [application note](https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/2R000000Hlit/77J00f9xeOhqu8XDfHrB0G54bEJGikO58GGYT__hyis) explaining what you are looking for.

**Comment by kvkc97** [comment]
I went through the application note and tried again. Error still exists. I have attached my code. Please review the same.
https://github.com/Lora-net/lr1110_updater_tool/pull/3

**Comment by matthieuantoine** [comment]
@kvkc97 - we do not accept contribution on this project. Your merge request will not be reviewed.

I can help if you share a snapshot of the SPI interface (+ busy and IRQ lines) so I can review if anything goes wrong while writing the new firmware.

**Comment by symovs** [comment]
hi @matthieuantoine 

It seems the firmware is getting flashed. However we are not able to read the firmware version after that. Our latest code is here - https://github.com/kvkc97/lr1110_updater_tool

![image](https://user-images.githubusercontent.com/66220236/137443303-0094e320-b757-459b-a2a4-0c80b77ebca6.png)

Our schematic can be accessed from here - https://drive.google.com/file/d/19OIvggdps_D96k0EEhb0PwoC_Q_ah1Jc/view?usp=sharing

**Comment by matthieuantoine** [comment]
@symovs - FYI, this is not a good idea to share your PIN here.

Here are some ideas:
* before resetting the chip at the end of the firmware update, do you wait for the BUSY line to go low?
* after the reset, do you wait for the BUSY line to go low before fetching the versions?

**Comment by symovs** [comment]
Thanks @matthieuantoine. Noted about the PIN. Just wanted to give you a full log of the output. This is a dev effort mostly and not  yet a production build. 

Before resetting the chip at the end of the firmware update, when we checked today the busy pin is high. Please suggest what we must do in this case - just wait here with a time out  and then reset the chip or is there anything else that can be done ?

**Comment by matthieuantoine** [comment]
> Before resetting the chip at the end of the firmware update, when we checked today the busy pin is high. Please suggest what we must do in this case - just wait here with a time out and then reset the chip or is there anything else that can be done ?

Just wait for BUSY line to go low. The last page is being updated so if you interrupt that, the firmware is corrupted.

**Comment by kvkc97** [comment]
The busy pin is not going low. We are waiting in a while loop and it comes out of the loop only when busy pin is low.

**Comment by matthieuantoine** [comment]
I really need to have SPI traces (including BUSY line) to see what is happening. There is no reason BUSY does not go LOW after the last page is updated - there is no difference with the previous one.

**Comment by kvkc97** [comment]
We changed the check of busy pin right after firmware updation and before reboot command. The busy pin is going low after firmware updation but after reboot command it is remaining high(even after setting NSS low and high in hal_read() function).

We tried the same code for updation to transreceiver mode and the firmware got updated correctly.
![image](https://user-images.githubusercontent.com/73599382/137591695-c12baf44-f8b5-4319-b6b3-4b5478055ea3.png)

**Comment by matthieuantoine** [comment]
Modem-E and transceiver drive the busy line differently - see the [SPI diagram in the reference manual](https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/2R000000USsZ/5EPFu4u.9lO9tdwmmsEMyMrllCWczDOVnPoaShaK2mg).

**Comment by kvkc97** [comment]
@matthieuantoine 
![image](https://user-images.githubusercontent.com/73599382/137632698-281a2d6e-fdc1-4d81-bf58-d37ee131c4bf.png)
We know modem-e busy pin polarity is high when in sleep. But it has to go low when NSS pin is toggled but this is not happening at our end.

**Comment by matthieuantoine** [comment]
After a reset with LoRa Basics Modem-E, you have to wait for the RESET event to be fired before you can talk to the chip. This event can be catch with the corresponding GPIO.

**Comment by kvkc97** [comment]
@matthieuantoine We have checked for the reset event at pin DIO9. The event is detected and pin goes high but busy pin is still high. Code is updated at repository.

**Comment by matthieuantoine** [comment]
As soon as the event is fired (i.e. the interrupt pin goes high), you can start a SPI transaction and fetch the event content.

**Comment by kvkc97** [comment]
After the event is fired, we called both the get_event() and get_version() functions. Both of them get stuck at the busy pin check in modem_hal_read(). The busy is pin high in both cases.

**Comment by symovs** [comment]
Hi @matthieuantoine 

Since the transceiver firmware is being updated properly and we are able to read the version information from LR1110 correctly we think our hardware is fine. Only the modem firmware is keeping us at bay with always high busy pin even after NSS pin toggling. Is there any possible errattic behaviour for the LR1110 modem firmware that you have observed at your end  ? Please help.

**Comment by matthieuantoine** [comment]
@symovs - no erratic behavior observed on our end. This project allows you to update a LR1110 with both types of firmware (transceiver and Modem-E) without any workaround needed.

I'll do a measure with my logic analyzer and share the end of the process so you can observe how it goes,

**Comment by symovs** [comment]
Thanks @matthieuantoine. Looking forward to your measurements from the logic analyzer.

**Comment by matthieuantoine** [comment]
At the end of the flash update, how do you leave the bootloader mode? With a reboot or a restart?

**Comment by kvkc97** [comment]
@matthieuantoine When the busy pin goes low after flash update, we are calling the function lr1110_bootloader_reboot()

**Comment by kvkc97** [comment]
@matthieuantoine were you able to debug the issue

**Comment by matthieuantoine** [comment]
![Screenshot from 2021-11-02 09-52-12](https://user-images.githubusercontent.com/44699865/139815661-a9c1c023-45c4-4c29-96b9-a71e7c583abd.png)

**Comment by matthieuantoine** [comment]
![Screenshot from 2021-11-02 09-55-55](https://user-images.githubusercontent.com/44699865/139815957-c31d0d4d-149b-4159-80c0-3adbe8c1a1b6.png)

**Comment by symovs** [comment]
Thanks @matthieuantoine  So the busy pin is going low at your end. Are the SPI clock modes different in transceiver mode and modem mode ? 

![image](https://user-images.githubusercontent.com/66220236/139820296-1ad20e1f-117e-4c2f-af0c-dbe5123db74b.png)

**Comment by matthieuantoine** [comment]
The busy pin is going low because of the glitch generated on the NSS line.

The sequence is the following:

1. Rising edge on EVENT line
2. Glitch generation on NSS line
3. Falling edge on BUSY line
4. Start SPI transmission

**Comment by symovs** [comment]
Thanks. 

Are the SPI clock modes different in transceiver mode and modem mode ? 

There is a SPI right after the NSS goes low and before it goes high ? Is this necessary and what purpose does it serve. Anyway that part is also in our code right now.

**Comment by matthieuantoine** [comment]
> Are the SPI clock modes different in transceiver mode and modem mode ?

No

> There is a SPI right after the NSS goes low and before it goes high ? Is this necessary and what purpose does it serve. Anyway that part is also in our code right now.

No, this is an artifact. Only the NSS glitch is required.

**Comment by symovs** [comment]
Ok Thanks. Let us check more at our end about what is happening.

**Comment by kvkc97** [comment]
@matthieuantoine 
We have updated our code removing the SPI transmit after the NSS goes low (we added that part earlier since it was mentioned in the github code). It was replaced by a 1 ms delay. We have also removed the system reset command right after reboot. 
After these changes we noticed the busy pin is not stuck at high, however in most cases it is stuck at low after the crc transmission (2nd while loop for busy pin check in hal_read). Also in certain cases, the busy pin is not stuck and code completely executes but the result obtained is zero(chip EUI and get version commands). The second case is very rare.
Could you share the timing diagram of the above mentioned sections? That is, SPI Transmit and 2nd busy pin check part.

**Comment by symovs** [comment]
@matthieuantoine any thoughts if you got some time to look into these would be very helpful.

**Comment by kvkc97** [comment]
@matthieuantoine are you able to understand the issue in our case. Would have be helpful if you could suggest any thought on this.

**Comment by kvkc97** [comment]
@matthieuantoine We have checked again but we are getting the same error. We modified the code as mentioned in the previous post to encorporate the signals as mentioned. However since we are students and cannot afford logic analyser for testing, we cannot verify the signals coming from the IC. Is there any method to check the issue without an logic analyser or any workdround to solve it. It would be really helpful for us if you could find a solution to this issue.

**Comment by sohaibqamar** [comment]
Hi @kvkc97 
Hope you are doing well.
Are you able to update the firmware for the LR1110 Transceiver?
I am trying to update the firmware for LR1110 Transceiver using NRF9160, my SPI transactions are working fine but I am not able to update the firmware.
Any help would be appreciated. 
Regards
Sohaib

**Comment by kvkc97** [comment]
@sohaibqamar Hi, i could not solve the issue in my case. If you get any clue regarding the solution, it would be helpful to me also.

**Comment by sohaibqamar** [comment]
> @sohaibqamar Hi, i could not solve the issue in my case. If you get any clue regarding the solution, it would be helpful to me also.

Hi @kvkc97
I am still unable to update the firmware of LR1110. I am using the Dev Kit of LR1110.
My LR1110 is unable to get out of the bootloader mode.
It's always returning 0xDF instead of 0x01, even after the successful firmware update process.
Any hint would be much appreciated.

**Comment by kvkc97** [comment]
@matthieuantoine @sohaibqamar 
This issue has been fixed. I have been using high level drivers for SPI communication earlier. When I changed them to low level drivers the firmware updation was successful. Thanks for the support.

**Comment by sohaibqamar** [comment]
> @matthieuantoine @sohaibqamar This issue has been fixed. I have been using high level drivers for SPI communication earlier. When I changed them to low level drivers the firmware updation was successful. Thanks for the support.

Hi @kvkc97 Can you upload the code so I can transform it into NRF9160?
I am using these [LR drivers](https://github.com/Lora-net/lr1110_driver).

**Comment by kvkc97** [comment]
> Hi @kvkc97 Can you upload the code so I can transform it into NRF9160? I am using these [LR drivers](https://github.com/Lora-net/lr1110_driver).

@sohaibqamar The code is available in the below link.
https://github.com/kvkc97/lr1110_updater_tool
Please note that there are some functions which are defined but no used and also some unwanted comments, just ignore them.

**Comment by sohaibqamar** [comment]
@kvkc97 Thanks for the code.
I have skimmed through your code. Are you updating the firmware for Modem or Transceiver?
Secondly, do I need to write hal.c for the modem as well in order to update the firmware for Transcsiver?
I have an opened issue in the [link](https://github.com/Lora-net/lr1110_updater_tool/issues/4), can you check and highlight the mistake?

**Comment by sohaibqamar** [comment]
hi @kvkc97 
After making changes exactly as of your code, I am getting the below messages. I have tried both Transceiver and Modem updates as well.
![image](https://user-images.githubusercontent.com/12796461/151550742-edc0697f-6558-4f87-afdb-584185c95258.png)

**Comment by matthieuantoine** [comment]
Do you use LoRa Basics Modem-E driver (https://github.com/Lora-net/lr1110_modem_driver) after the update? The protocol is slightly different from the transceiver one.

**Comment by kvkc97** [comment]
@sohaibqamar 
I am updating the firmware to Modem and then using lr1110 modem driver. I dont think modem_hal.c is required to update to transceiver. 
The error can be due to an issue in spi communication. I had similar error while using spi high level drivers. That's why I shifted to low level driver and issue was resolved.

**Comment by sohaibqamar** [comment]
> Do you use LoRa Basics Modem-E driver (https://github.com/Lora-net/lr1110_modem_driver) after the update? The protocol is slightly different from the transceiver one.

Hi @matthieuantoine thanks for the response.
I am using version 6 of lr1110 [driver](https://github.com/Lora-net/lr1110_driver).
Both Transceiver and Modem-E drivers have **lr1110_bootloader.c** file. Is there any difference in both files?
Assume that I just need to update the firmware for Transceiver, please guide me for that. Thanks

**Comment by sohaibqamar** [comment]
My SPI is working fine as I was able to successfully get the Wi-Fi scanning results.

**Comment by sohaibqamar** [comment]
> I am updating the firmware to Modem and then using lr1110 modem driver. I dont think modem_hal.c is required to update to transceiver.

Thanks for the response.

> The error can be due to an issue in spi communication. I had similar error while using spi high level drivers. That's why I shifted to low level driver and issue was resolved.

I don't understand the difference between high-level and low-level SPI drivers, did you change the SPI mode?
Do you have any information about the SPI mode of LR1110? I can configure SPI mode & frequency in my controller NRF9160.

**Comment by kvkc97** [comment]
@sohaibqamar 
My SPI in high level driver was also working fine for WiFi scanning but there were some issues while firmware updation. I didnot make any changes in LR1110 for SPI mode. The changes were done at the controller side only.

**Comment by sohaibqamar** [comment]
> @sohaibqamar My SPI in high level driver was also working fine for WiFi scanning but there were some issues while firmware updation. I didnot make any changes in LR1110 for SPI mode. The changes were done at the controller side only.

@kvkc97 Hi, I was busy with other things recently, I have checked your code and replicated things in my code same for SPI settings, etc. Can you tell me the difference between low level and high-level spi drivers for STM32, as there are no high level and low-level spi drivers for NRF9160 I'm using to update the firmware of LR1110. Will be waiting for your response.
